# Generated by Django 2.2.6 on 2019-10-20 17:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Profesor', 'Profesor'), ('Secretaría', 'Secretaría')], max_length=20, verbose_name='Rol')),
                ('tipo_documento', models.CharField(choices=[('CC-Cédula de ciudadanía', 'CC-Cédula de ciudadanía'), ('CE-Cédula de Extranjería', 'CE-Cédula de Extranjería'), ('TI-Tarjeta de identidad', 'TI-Tarjeta de identidad'), ('PA-Pasaporte', 'PA-Pasaporte')], max_length=50, verbose_name='Tipo de documento')),
                ('numero_documento', models.IntegerField()),
            ],
            options={
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
